spring:
  application:
    name: order-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://order-db:5432/order-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8081