services:
  master:
    image: bitnami/postgresql:16.3.0
    container_name: generate-number-service
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: generate-number-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres